"""Add pengumuman tables

Revision ID: 275075d94af7
Revises: e26cc16719d4
Create Date: 2025-05-22 10:30:21.362343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275075d94af7'
down_revision = 'e26cc16719d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kategori_pengumuman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deskripsi', sa.String(length=255), nullable=True))
        batch_op.alter_column('nama',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('slug')

    with op.batch_alter_table('pengumuman', schema=None) as batch_op:
        batch_op.alter_column('judul',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('konten',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengumuman', schema=None) as batch_op:
        batch_op.alter_column('konten',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('judul',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('kategori_pengumuman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('nama',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('deskripsi')

    # ### end Alembic commands ###
