"""versi baru

Revision ID: 4cea4b2d67ab
Revises: 
Create Date: 2025-05-15 13:08:25.599299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cea4b2d67ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurusan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('kuota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('kategori_pengumuman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendaftaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('no_pendaftaran', sa.String(length=20), nullable=True),
    sa.Column('nisn', sa.String(length=10), nullable=True),
    sa.Column('nik', sa.String(length=16), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('agama', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('rt', sa.String(length=3), nullable=True),
    sa.Column('rw', sa.String(length=3), nullable=True),
    sa.Column('kelurahan', sa.String(length=50), nullable=True),
    sa.Column('kecamatan', sa.String(length=50), nullable=True),
    sa.Column('kota', sa.String(length=50), nullable=True),
    sa.Column('kode_pos', sa.String(length=5), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('nama_ayah', sa.String(length=100), nullable=True),
    sa.Column('pekerjaan_ayah', sa.String(length=50), nullable=True),
    sa.Column('nama_ibu', sa.String(length=100), nullable=True),
    sa.Column('pekerjaan_ibu', sa.String(length=50), nullable=True),
    sa.Column('no_hp_ortu', sa.String(length=15), nullable=True),
    sa.Column('asal_sekolah', sa.String(length=100), nullable=True),
    sa.Column('npsn_sekolah', sa.String(length=8), nullable=True),
    sa.Column('nilai_rata_rata', sa.Float(), nullable=True),
    sa.Column('jurusan_id', sa.Integer(), nullable=True),
    sa.Column('jalur_pendaftaran', sa.String(length=20), nullable=True),
    sa.Column('status_pendaftaran', sa.String(length=20), nullable=True),
    sa.Column('status_seleksi', sa.String(length=20), nullable=True),
    sa.Column('no_urut', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jurusan_id'], ['jurusan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn'),
    sa.UniqueConstraint('no_pendaftaran')
    )
    op.create_table('pengumuman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=200), nullable=True),
    sa.Column('konten', sa.Text(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori_pengumuman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berkas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=True),
    sa.Column('jenis', sa.String(length=50), nullable=True),
    sa.Column('nama_file', sa.String(length=255), nullable=True),
    sa.Column('ukuran', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daftar_ulang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('verifikasi_admin', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pembayaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftaran_id', sa.Integer(), nullable=True),
    sa.Column('no_invoice', sa.String(length=20), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('metode', sa.String(length=50), nullable=True),
    sa.Column('bukti', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tanggal_bayar', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pendaftaran_id'], ['pendaftaran.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_invoice')
    )
    op.create_table('berkas_daftar_ulang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daftar_ulang_id', sa.Integer(), nullable=True),
    sa.Column('jenis', sa.String(length=50), nullable=True),
    sa.Column('nama_file', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['daftar_ulang_id'], ['daftar_ulang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('berkas_daftar_ulang')
    op.drop_table('pembayaran')
    op.drop_table('daftar_ulang')
    op.drop_table('berkas')
    op.drop_table('pengumuman')
    op.drop_table('pendaftaran')
    op.drop_table('activity_log')
    op.drop_table('user')
    op.drop_table('kategori_pengumuman')
    op.drop_table('jurusan')
    # ### end Alembic commands ###
