"""add status to pendaftaran

Revision ID: 880422ce6ef8
Revises: bfa13e8ba886
Create Date: 2025-05-21 08:15:10.780576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880422ce6ef8'
down_revision = 'bfa13e8ba886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
