"""Initial migration

Revision ID: b682df73dd37
Revises: 
Create Date: 2025-05-08 13:18:38.181479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b682df73dd37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pendaftar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('nisn', sa.String(length=10), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('asal_sekolah', sa.String(length=100), nullable=False),
    sa.Column('jalur_pendaftaran', sa.String(length=20), nullable=False),
    sa.Column('tanggal_daftar', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn')
    )
    op.create_table('berkas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftar_id', sa.Integer(), nullable=False),
    sa.Column('kartu_keluarga', sa.String(length=200), nullable=True),
    sa.Column('akta_kelahiran', sa.String(length=200), nullable=True),
    sa.Column('rapor', sa.String(length=200), nullable=True),
    sa.Column('surat_keterangan', sa.String(length=200), nullable=True),
    sa.Column('tanggal_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pendaftar_id'], ['pendaftar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftar_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pendaftar_id'], ['pendaftar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('berkas')
    op.drop_table('pendaftar')
    op.drop_table('user')
    # ### end Alembic commands ###
