"""Add Jurusan model

Revision ID: c1da5e79828f
Revises: 275075d94af7
Create Date: 2025-05-22 11:00:57.456769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1da5e79828f'
down_revision = '275075d94af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jurusan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('kode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jurusan', schema=None) as batch_op:
        batch_op.alter_column('kode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
