"""Update models untuk PPDB

Revision ID: c7c6e41ec448
Revises: b682df73dd37
Create Date: 2025-05-13 08:42:02.482987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c6e41ec448'
down_revision = 'b682df73dd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pembayaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pendaftar_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('bukti_pembayaran', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tanggal_bayar', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pendaftar_id'], ['pendaftar.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('berkas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_berkas', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('nama_file', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('pendaftar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agama', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('no_hp', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('nilai_un', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('jurusan_pilihan', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('nisn',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('jenis_kelamin',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('jalur_pendaftaran',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pendaftar', schema=None) as batch_op:
        batch_op.alter_column('jalur_pendaftaran',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('jenis_kelamin',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.alter_column('nisn',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('jurusan_pilihan')
        batch_op.drop_column('nilai_un')
        batch_op.drop_column('no_hp')
        batch_op.drop_column('agama')

    with op.batch_alter_table('berkas', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('nama_file')
        batch_op.drop_column('jenis_berkas')

    op.drop_table('pembayaran')
    # ### end Alembic commands ###
