"""Add jurusan_pilihan column to pendaftaran

Revision ID: d0052755e543
Revises: 880422ce6ef8
Create Date: 2025-05-21 09:34:15.735611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0052755e543'
down_revision = '880422ce6ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurusan_pilihan', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.drop_column('jurusan_pilihan')

    # ### end Alembic commands ###
