"""Update pendaftaran fields

Revision ID: e26cc16719d4
Revises: d0052755e543
Create Date: 2025-05-22 09:50:53.162192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26cc16719d4'
down_revision = 'd0052755e543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('berkas', schema=None) as batch_op:
        batch_op.alter_column('pendaftaran_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ukuran')

    with op.batch_alter_table('pembayaran', schema=None) as batch_op:
        batch_op.alter_column('pendaftaran_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftaran', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('keterangan')

    with op.batch_alter_table('pembayaran', schema=None) as batch_op:
        batch_op.alter_column('pendaftaran_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('berkas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ukuran', sa.INTEGER(), nullable=True))
        batch_op.alter_column('pendaftaran_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
